Payment
Rimberse/Watches-e-commerce-platform pull request #3
Opened 2022-07-01 11:51 UTC by jessyVy

2022-07-01 18:01 UTC, Rimberse commented
@jessyVy Tu as fini de travailler sur cette branche ? D'ailleurs je vois que tu as de conflits, serait-il possible de les corriger, stp ?
Notifs moi quand tu finiras de travailler sur cette branche, pour je puisse faire le review et merger !

2022-07-01 20:45 UTC, jessyVy commented
Oui j'ai fini sur cette branche, et il n'y a plus de conflits maintenant normalement

2022-07-01 23:42 UTC, Rimberse requested changes
@jessyVy Dits moi si tu pourras introduire les changements demandes, stp ?
Sinon je vais le faire moi-même, mais cela serait bien si tu peux faire des changements, je vais travailler sur d'autres sujets.

2022-07-01 23:42 UTC, Rimberse commented on Backend/src/index.js
> +});
Je comprends pas trop l'utilité de cette méthode, vu que le table panier est utilise uniquement pour stocker les contenus du panier au cas ou le client se déconnecte

2022-07-01 23:42 UTC, Rimberse commented on Backend/src/index.js
> +
L'endpoint sera plutôt "api/transaction", vu que il existe déjà une méthode qui alimente la table "Transactions" et il est appelé en faisant un POST

2022-07-01 23:42 UTC, Rimberse commented on Backend/src/services/shop.js
> +
Pareil comme précédemment

2022-07-01 23:42 UTC, Rimberse commented on Backend/src/services/shop.js
> +}
C'est bon, mais faudra déplacer la fonction dans le fichier transaction.js et la nom a réfléchir (plutôt getAll pour être cohérent avec la reste)

2022-07-01 23:42 UTC, Rimberse commented on Frontend/.env
> +REACT_APP_PAYPAL_CLIENT_ID=AVzSRfz6W2mUqu_Vx4wubVEk5C0q94tpusPIjiNMEd_hC4YyPmTt8qyE0BWRNnGNdZjgfONQTP141zlw
Tu as oublié d'ajouter .env dans gitignore. C'est dangereux d'exposer les cles sur un repo git publique.

2022-07-01 23:42 UTC, Rimberse commented on Frontend/src/App.css
> +  padding-top: 3%;
Faut créer une classe Navbar.css et faire le styling dedans, mais c'est pas grave

2022-07-01 23:42 UTC, Rimberse commented on Frontend/src/App.js
> +    </body>
Sans body, le Navbar doit être a l'intérieur de App
App est le component mère pour tous les components React

2022-07-01 23:42 UTC, Rimberse commented on Frontend/src/components/Logs/Logs.js
> +const Logs = () => {
Le nom faut changer aussi, vu que au niveau de backend on change

2022-07-01 23:42 UTC, Rimberse commented on Frontend/src/components/Logs/style.css
> +.card {
Appelle le fichier Logs.css et mets le dans le dossier dédié au Styling "src/Styles"

2022-07-01 23:42 UTC, Rimberse commented on Frontend/src/components/Payment/style.css
> +.title{
Pareil comme pour les logs. Dossier "Styles"

2022-07-01 23:42 UTC, Rimberse commented on Frontend/src/data/MenuData.js
> +export const menuData = [
Ca doit être dans Navbar comme variable. Pas besoin de créer un fichier a part

2022-07-01 23:42 UTC, Rimberse commented on Frontend/src/index.js
> +      </Router>
Les routers faudra faire plutôt dans App.js, comme dans le projet que on a fait avant. Mais, je m'en préoccuperai plus tard

2022-07-02 07:42 UTC, jessyVy commented on Backend/src/index.js
> +});
Mon système de paiement utilise la liste d'articles qu'il y a dans le panier pour calculer le prix à payer, sinon je vois pas comment faire :/

2022-07-02 09:25 UTC, Rimberse commented on Backend/src/index.js
> +});
@jessyVy Faut utiliser soit checkout dans le fichier Cart.js soit calculateTotal (si tu veux juste la prix total). J'ai fait express de créer le button checkout pour le renvoyer après a ton payment. Le panier est volatile, stocke comme un objet JS, y a pas de stockage au niveau de BDD, uniquement quand le client a déjà réalisé son achat on stocke dans transactions.

2022-07-03 20:07 UTC, Rimberse approved these changes

2022-07-03 20:08 UTC, merged